### ISSUE TITLE
Suggestion: page missing a title

### ISSUE THREAD

**Issue by JamesSkemp** [Crypto2557/Crypto2557.github.io#67]
First, big fan of the tool.

Second, in https://github.com/Crypto2557/Crypto2557.github.io/blob/master/index.html it would be a good idea to add a `<title></title>`.

I was going to submit a merge request, but you don't really have a title defined anywhere within the site or code, so I wasn't 100% sure what to use. It's an easy addition, but more than happy to submit a merge request if I know what the title of the tool is. :)

**Comment by NotHarroweD** [comment]
Hey, thanks for the interest James! The working title of the tool is Endless Farming, so for titling the page it's currently done this way:

<h5 class="modal-title">Endless Farming</h5>

**Comment by JamesSkemp** [comment]
So my initial guess was correct.

I've submitted a merge request with the `title` addition so that the tool's name is reflected in the browser.

Thanks!

**Comment by Crypto2557** [comment]
Fixed in upcoming patch
