### ISSUE TITLE
Pets Tab

### ISSUE THREAD

**Issue by Warlockx** [Crypto2557/Crypto2557.github.io#70]
TabControl inside the modal that pops up when the user clicks on the pet, the additional tab inside the modal will give more information about the pet box.

Additional Information: 
Where the pet fragment is located xx-xx in SH

Ability to do maths inside the input box (handled by javascript):
The user would click the star which would increase the amount of fragments farmed,
then he would be able to do current_value + x, and when he input lost focus the value would resolve.

**Comment by Crypto2557** [comment]
Won't be added here but possibly in version 2 of the website
