### ISSUE TITLE
Suggestion: Support tracking all pets in interface

### ISSUE THREAD

**Issue by JamesSkemp** [Crypto2557/Crypto2557.github.io#76]
It would be helpful to be able to track all of the pets in the interface, even if they can't be obtained via Spirit Highlands.

One or more options could be added under the Pets navigation item. Personally I would rather have one, but I assume the interface could support multiple pages displaying similar information.

**Comment by Crypto2557** [comment]
The website now also tracks ss1-5, event, greek and zodiac pets. Raid and outland battle are still missing

**Comment by JamesSkemp** [comment]
Yup, noticed this when I navigated to another tab shortly after the reset today. Looks great! Lot of really great progress on the site. :)

**Comment by JamesSkemp** [comment]
Nice job on adding raid and outland pets.

I'm pretty sure this is now complete?

**Comment by Crypto2557** [comment]
True. Guess time to close this issue. :D
